logging:
  level:
    root: INFO

  file:
    path: logs # 로그 파일이 저장될 디렉토리

  logback:
    rollingpolicy:
      file-name-pattern: app.%d{yyyy-MM-dd}.%i.log # 날짜와 인덱스별로 파일 분할
      clean-history-on-start: false
      max-file-size: 10MB
      max-history: 14
      total-size-cap: 1GB

  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(%5p) %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} : %m%n%wEx"
    level: DEBUG
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    dateformat: yyyy-MM-dd HH:mm:ss
